require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::PublishersController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::Publisher. As you add validations to Admin::Publisher, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::PublishersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all admin_publishers as @admin_publishers" do
      publisher = Admin::Publisher.create! valid_attributes
      get :index, {}, valid_session
      assigns(:admin_publishers).should eq([publisher])
    end
  end

  describe "GET show" do
    it "assigns the requested publisher as @publisher" do
      publisher = Admin::Publisher.create! valid_attributes
      get :show, {:id => publisher.to_param}, valid_session
      assigns(:publisher).should eq(publisher)
    end
  end

  describe "GET new" do
    it "assigns a new publisher as @publisher" do
      get :new, {}, valid_session
      assigns(:publisher).should be_a_new(Admin::Publisher)
    end
  end

  describe "GET edit" do
    it "assigns the requested publisher as @publisher" do
      publisher = Admin::Publisher.create! valid_attributes
      get :edit, {:id => publisher.to_param}, valid_session
      assigns(:publisher).should eq(publisher)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::Publisher" do
        expect {
          post :create, {:publisher => valid_attributes}, valid_session
        }.to change(Admin::Publisher, :count).by(1)
      end

      it "assigns a newly created publisher as @publisher" do
        post :create, {:publisher => valid_attributes}, valid_session
        assigns(:publisher).should be_a(Admin::Publisher)
        assigns(:publisher).should be_persisted
      end

      it "redirects to the created publisher" do
        post :create, {:publisher => valid_attributes}, valid_session
        response.should redirect_to(Admin::Publisher.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved publisher as @publisher" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Publisher.any_instance.stub(:save).and_return(false)
        post :create, {:publisher => {}}, valid_session
        assigns(:publisher).should be_a_new(Admin::Publisher)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Publisher.any_instance.stub(:save).and_return(false)
        post :create, {:publisher => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested publisher" do
        publisher = Admin::Publisher.create! valid_attributes
        # Assuming there are no other admin_publishers in the database, this
        # specifies that the Admin::Publisher created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::Publisher.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => publisher.to_param, :publisher => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested publisher as @publisher" do
        publisher = Admin::Publisher.create! valid_attributes
        put :update, {:id => publisher.to_param, :publisher => valid_attributes}, valid_session
        assigns(:publisher).should eq(publisher)
      end

      it "redirects to the publisher" do
        publisher = Admin::Publisher.create! valid_attributes
        put :update, {:id => publisher.to_param, :publisher => valid_attributes}, valid_session
        response.should redirect_to(publisher)
      end
    end

    describe "with invalid params" do
      it "assigns the publisher as @publisher" do
        publisher = Admin::Publisher.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Publisher.any_instance.stub(:save).and_return(false)
        put :update, {:id => publisher.to_param, :publisher => {}}, valid_session
        assigns(:publisher).should eq(publisher)
      end

      it "re-renders the 'edit' template" do
        publisher = Admin::Publisher.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Publisher.any_instance.stub(:save).and_return(false)
        put :update, {:id => publisher.to_param, :publisher => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested publisher" do
      publisher = Admin::Publisher.create! valid_attributes
      expect {
        delete :destroy, {:id => publisher.to_param}, valid_session
      }.to change(Admin::Publisher, :count).by(-1)
    end

    it "redirects to the admin_publishers list" do
      publisher = Admin::Publisher.create! valid_attributes
      delete :destroy, {:id => publisher.to_param}, valid_session
      response.should redirect_to(admin_publishers_url)
    end
  end

end
